### PR TITLE
Proposed fix for issue #49.

### PR DESCRIPTION
**Pull request by manwar**
Hi @Grinnz 

Please review the PR, propose to fix issue #49 

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by perigrin** [comment]
Mohammad, thanks for the work on getting this into a PR. 

I've left a question on #49 to see if this should be accepted or not.

**Comment by manwar** [comment]
@perigrin I am merely following the suggestions. I don't have personal opinion about this to be honest very honest with you.

I am getting an idea, I shouldn't create PR for issues listed as it hasn't been approved/accepted by the distribution owner.

**Comment by karenetheridge** [comment]
Creating pull requests for suggestions that haven't been discussed yet is not helpful -- the actual act of updating the yaml file is trivial and we do not need help with that. It is the determination of the content of the file that is where the effort lies.

**Comment by manwar** [comment]
I misunderstood the blog post asking for help.
Feel free to close others as well :-)

**Pull request closed without merging**
